name: .NET

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: HomeWork1/HomeWork1
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: HomeWork1/HomeWork1Test
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with: 
        file: HomeWork1/TestResults/CovReport.xml
